name: PHP Standards
on:
  push:
    branches:
      - 'main'
    paths:
      - '**.php'
      - '**.json'
  pull_request:
    branches:
      - '**'
    paths:
      - '**.php'
      - '**.json'

jobs:
  build:
    name: PHP Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install PHP
        uses: shivammathur/setup-php@fcafdd6392932010c2bd5094439b8e33be2a8a09 # v2.37.0
        with:
          php-version: '8.1'
          coverage: none

      - name: Echo PHP & Composer versions
        run: |
          php --version
          php -m
          composer --version

      - name: Get Composer Cache Directory
        id: composer-cache-dir
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache PHP Dependencies
        id: composer-cache
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-7.2-${{ hashFiles('composer.lock') }}

      - name: Install PHP Dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: PHPCS cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: tests/cache
          key: ${{ runner.os }}-phpcs-7.2-${{ hashFiles('plugin.php') }}

      - name: Run the tests
        run: |
          composer lint
        env:
          MYSQL_DATABASE: wordpress
          WP_TESTS_DB_PASS: root
